-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.


CREATE TABLE "candidates" (
    "CAND_ID" text   NOT NULL,
    "CAND_NAME" text   NOT NULL,
    "CAND_PTY_AFFILIATION" text   NOT NULL,
    "CAND_ELECTION_YR" text   NOT NULL,
    "CAND_OFFICE_ST" text   NOT NULL,
    "CAND_OFFICE" text   NOT NULL,
    "CAND_OFFICE_DISTRICT" text   NOT NULL,
    "CMTE_ZIP" text   NOT NULL,
    "CMTE_DSGN" text   NOT NULL,
    "CAND_ICI" text   NOT NULL,
    "CAND_STATUS" text   NOT NULL,
    "CAND_PCC" text   NOT NULL,
    "CAND_ST1" text   NOT NULL,
    "CAND_ST2" text   NOT NULL,
    "CAND_CITY" text   NOT NULL,
    "CAND_ST" text   NOT NULL,
    "CAND_ZIP" text   NOT NULL
);

CREATE TABLE "committees" (
    "CMTE_ID" text   NOT NULL,
    "CMTE_NM" text   NOT NULL,
    "TRES_NM" text   NOT NULL,
    "CMTE_ST1" text   NOT NULL,
    "CMTE_ST2" text   NOT NULL,
    "CMTE_CITY" text   NOT NULL,
    "CMTE_ST" text   NOT NULL,
    "CMTE_ZIP" text   NOT NULL,
    "CMTE_DSGN" text   NOT NULL,
    "CMTE_TP" text   NOT NULL,
    "CMTE_PTY_AFFILIATION" text   NOT NULL,
    "CMTE_FILING_FREQ" text   NOT NULL,
    "ORG_TP" text   NOT NULL,
    "CONNECTED_ORG_NM" text   NOT NULL,
    "CAND_ID" text   NOT NULL
);

CREATE TABLE "donations" (
    "CMTE_ID" text   NOT NULL,
    "AMNDT_IND" text   NOT NULL,
    "RPT_TP" text   NOT NULL,
    "TRANSACTION_PGI" text   NOT NULL,
    "IMAGE_NUM" text   NOT NULL,
    "TRANSACTION_TP" text   NOT NULL,
    "ENTITY_TP" text   NOT NULL,
    "NAME" text   NOT NULL,
    "CITY" text   NOT NULL,
    "STATE" text   NOT NULL,
    "ZIP" text   NOT NULL,
    "EMPLOYER" text   NOT NULL,
    "OCCUPATION" text   NOT NULL,
    "TRANSACTION_DT" text   NOT NULL,
    "TRANSACTION_AMT" integer,   NOT NULL,
    "OTHER_ID" text   NOT NULL,
    "TRAN_ID" text   NOT NULL,
    "FILE_NUM" text   NOT NULL,
    "MEMO_CD" text   NOT NULL,
    "MEMO_TEXT" text   NOT NULL,
    "SUB_ID" text   NOT NULL
);

CREATE TABLE "education" (
    "FIPS Code" integer   NOT NULL,
    "State" text   NOT NULL,
    "Area name" text   NOT NULL,
    "2003 Rural-urban Continuum Code" double   NOT NULL,
    "2003 Urban Influence Code" double   NOT NULL,
    "2013 Rural-urban Continuum Code" double   NOT NULL,
    "2013 Urban Influence Code" double   NOT NULL,
    "Less than a high school diploma 1970" double   NOT NULL,
    "High school diploma only 1970" double   NOT NULL,
    "Some college (1-3 years) 1970" double   NOT NULL,
    "Four years of college or higher 1970" double   NOT NULL,
    "Percent of adults with less than a high school diploma 1970" double   NOT NULL,
    "Percent of adults with a high school diploma only 1970" double   NOT NULL,
    "Percent of adults completing some college (1-3 years) 1970" double   NOT NULL,
    "Percent of adults completing college or higher 1970" double   NOT NULL,
    "Less than a high school diploma 1980" double   NOT NULL,
    "High school diploma only 1980" double   NOT NULL,
    "Some college (1-3 years) 1980" double   NOT NULL,
    "Four years of college or higher 1980" double   NOT NULL,
    "Percent of adults with less than a high school diploma 1980" double   NOT NULL,
    "Percent of adults with a high school diploma only 1980" double   NOT NULL,
    "Percent of adults completing some college (1-3 years) 1980" double   NOT NULL,
    "Percent of adults completing college or higher 1980" double   NOT NULL,
    "Less than a high school diploma 1990" double   NOT NULL,
    "High school diploma only 1990" double   NOT NULL,
    "Some college or associate's degree 1990" double   NOT NULL,
    "Bachelor's degree or higher 1990" double   NOT NULL,
    "Percent of adults with less than a high school diploma 1990" double   NOT NULL,
    "Percent of adults with a high school diploma only 1990" double   NOT NULL,
    "Percent of adults completing some college 1990" double   NOT NULL,
    "Percent of adults with a bachelor's degree or higher 1990" double   NOT NULL,
    "Less than a high school diploma 2000" double   NOT NULL,
    "High school diploma only 2000" double   NOT NULL,
    "Some college or associate's degree 2000" double   NOT NULL,
    "Bachelor's degree or higher 2000" double   NOT NULL,
    "Percent of adults with less than a high school diploma 2000" double   NOT NULL,
    "Percent of adults with a high school diploma only 2000" double   NOT NULL,
    "Percent of adults completing some college 2000" double   NOT NULL,
    "Percent of adults with a bachelor's degree or higher 2000" double   NOT NULL,
    "Less than a high school diploma 2014-18" double   NOT NULL,
    "High school diploma only 2014-18" double   NOT NULL,
    "Some college or associate's degree 2014-18" double   NOT NULL,
    "Bachelor's degree or higher 2014-18" double   NOT NULL,
    "Percent of adults with less than a high school diploma 2014-18" double   NOT NULL,
    "Percent of adults with a high school diploma only 2014-18" double   NOT NULL,
    "Percent of adults completing some college 2014-18" double   NOT NULL,
    "Percent of adults with a bachelor's degree or higher 2014-18" double   NOT NULL
);

CREATE TABLE "postal_codes" (
    "zip" integer   NOT NULL,
    "county" text   NOT NULL,
    "state" text   NOT NULL,
    "stcountyfp" integer   NOT NULL,
    "classfp" text   NOT NULL
);

CREATE TABLE "unemployment" (
    "fips" integer,   NOT NULL,
    "state" text   NOT NULL,
    "county" text   NOT NULL,
    "num_deaths" integer,   NOT NULL,
    "years_of_potential_life_lost_rate" double   NOT NULL,
    "95percent_ci_low" double   NOT NULL,
    "95percent_ci_high" double   NOT NULL,
    "quartile" integer,   NOT NULL,
    "ypll_rate_aian" double   NOT NULL,
    "ypll_rate_aian_95percent_ci_low" double   NOT NULL,
    "ypll_rate_aian_95percent_ci_high" double   NOT NULL,
    "ypll_rate_asian" double   NOT NULL,
    "ypll_rate_asian_95percent_ci_low" double   NOT NULL,
    "ypll_rate_asian_95percent_ci_high" double   NOT NULL,
    "ypll_rate_black" double   NOT NULL,
    "ypll_rate_black_95percent_ci_low" double   NOT NULL,
    "ypll_rate_black_95percent_ci_high" double   NOT NULL,
    "ypll_rate_hispanic" double   NOT NULL,
    "ypll_rate_hispanic_95percent_ci_low" double   NOT NULL,
    "ypll_rate_hispanic_95percent_ci_high" double   NOT NULL,
    "ypll_rate_white" double   NOT NULL,
    "ypll_rate_white_95percent_ci_low" double   NOT NULL,
    "ypll_rate_white_95percent_ci_high" double   NOT NULL,
    "percent_fair_or_poor_health" double   NOT NULL,
    "95percent_ci_low_2" double   NOT NULL,
    "95percent_ci_high_2" double   NOT NULL,
    "quartile_2" integer,   NOT NULL,
    "average_number_of_physically_unhealthy_days" double   NOT NULL,
    "95percent_ci_low_3" double   NOT NULL,
    "95percent_ci_high_3" double   NOT NULL,
    "quartile_3" integer,   NOT NULL,
    "average_number_of_mentally_unhealthy_days" double   NOT NULL,
    "95percent_ci_low_4" double   NOT NULL,
    "95percent_ci_high_4" double   NOT NULL,
    "quartile_4" integer,   NOT NULL,
    "unreliable" text   NOT NULL,
    "percent_low_birthweight" double   NOT NULL,
    "95percent_ci_low_5" double   NOT NULL,
    "95percent_ci_high_5" double   NOT NULL,
    "quartile_5" integer,   NOT NULL,
    "percent_lbw_aian" double   NOT NULL,
    "percent_lbw_aian_95percent_ci_low" integer,   NOT NULL,
    "percent_lbw_aian_95percent_ci_high" double   NOT NULL,
    "percent_lbw_asian" double   NOT NULL,
    "percent_lbw_asian_95percent_ci_low" double   NOT NULL,
    "percent_lbw_asian_95percent_ci_high" double   NOT NULL,
    "percent_lbw_black" double   NOT NULL,
    "percent_lbw_black_95percent_ci_low" double   NOT NULL,
    "percent_lbw_black_95percent_ci_high" double   NOT NULL,
    "percent_lbw_hispanic" double   NOT NULL,
    "percent_lbw_hispanic_95percent_ci_low" double   NOT NULL,
    "percent_lbw_hispanic_95percent_ci_high" double   NOT NULL,
    "percent_lbw_white" double   NOT NULL,
    "percent_lbw_white_95percent_ci_low" double   NOT NULL,
    "percent_lbw_white_95percent_ci_high" double   NOT NULL,
    "percent_smokers" double   NOT NULL,
    "95percent_ci_low_6" double   NOT NULL,
    "95percent_ci_high_6" double   NOT NULL,
    "quartile_6" integer,   NOT NULL,
    "percent_adults_with_obesity" double   NOT NULL,
    "95percent_ci_low_7" double   NOT NULL,
    "95percent_ci_high_7" double   NOT NULL,
    "quartile_7" integer,   NOT NULL,
    "food_environment_index" double   NOT NULL,
    "quartile_8" integer,   NOT NULL,
    "percent_physically_inactive" double   NOT NULL,
    "95percent_ci_low_8" double   NOT NULL,
    "95percent_ci_high_8" double   NOT NULL,
    "quartile_9" integer,   NOT NULL,
    "percent_with_access_to_exercise_opportunities" double   NOT NULL,
    "quartile_10" integer,   NOT NULL,
    "percent_excessive_drinking" double   NOT NULL,
    "95percent_ci_low_9" double   NOT NULL,
    "95percent_ci_high_9" double   NOT NULL,
    "quartile_11" integer,   NOT NULL,
    "num_alcohol_impaired_driving_deaths" integer,   NOT NULL,
    "num_driving_deaths" integer,   NOT NULL,
    "percent_driving_deaths_with_alcohol_involvement" double   NOT NULL,
    "95percent_ci_low_10" double   NOT NULL,
    "95percent_ci_high_10" double   NOT NULL,
    "quartile_12" integer,   NOT NULL,
    "num_chlamydia_cases" integer,   NOT NULL,
    "chlamydia_rate" double   NOT NULL,
    "quartile_13" integer,   NOT NULL,
    "teen_birth_rate" double   NOT NULL,
    "95percent_ci_low_11" double   NOT NULL,
    "95percent_ci_high_11" double   NOT NULL,
    "quartile_14" integer,   NOT NULL,
    "teen_birth_rate_aian" double   NOT NULL,
    "teen_birth_rate_aian_95percent_ci_low" double   NOT NULL,
    "teen_birth_rate_aian_95percent_ci_high" double   NOT NULL,
    "teen_birth_rate_asian" double   NOT NULL,
    "teen_birth_rate_asian_95percent_ci_low" double   NOT NULL,
    "teen_birth_rate_asian_95percent_ci_high" double   NOT NULL,
    "teen_birth_rate_black" double   NOT NULL,
    "teen_birth_rate_black_95percent_ci_low" double   NOT NULL,
    "teen_birth_rate_black_95percent_ci_high" double   NOT NULL,
    "teen_birth_rate_hispanic" double   NOT NULL,
    "teen_birth_rate_hispanic_95percent_ci_low" double   NOT NULL,
    "teen_birth_rate_hispanic_95percent_ci_high" double   NOT NULL,
    "teen_birth_rate_white" double   NOT NULL,
    "teen_birth_rate_white_95percent_ci_low" double   NOT NULL,
    "teen_birth_rate_white_95percent_ci_high" double   NOT NULL,
    "num_uninsured" integer,   NOT NULL,
    "percent_uninsured" double   NOT NULL,
    "95percent_ci_low_12" double   NOT NULL,
    "95percent_ci_high_12" double   NOT NULL,
    "quartile_15" integer,   NOT NULL,
    "num_primary_care_physicians" integer,   NOT NULL,
    "primary_care_physicians_rate" double   NOT NULL,
    "primary_care_physicians_ratio" text   NOT NULL,
    "quartile_16" integer,   NOT NULL,
    "num_dentists" integer,   NOT NULL,
    "dentist_rate" double   NOT NULL,
    "dentist_ratio" text   NOT NULL,
    "quartile_17" integer,   NOT NULL,
    "num_mental_health_providers" integer,   NOT NULL,
    "mental_health_provider_rate" double   NOT NULL,
    "mental_health_provider_ratio" text   NOT NULL,
    "quartile_18" integer,   NOT NULL,
    "preventable_hospitalization_rate" integer,   NOT NULL,
    "quartile_19" integer,   NOT NULL,
    "preventable_hosp_rate_aian" integer,   NOT NULL,
    "preventable_hosp_rate_asian" integer,   NOT NULL,
    "preventable_hosp_rate_black" integer,   NOT NULL,
    "preventable_hosp_rate_hispanic" integer,   NOT NULL,
    "preventable_hosp_rate_white" integer,   NOT NULL,
    "percent_with_annual_mammogram" integer,   NOT NULL,
    "quartile_20" integer,   NOT NULL,
    "percent_screened_aian" integer,   NOT NULL,
    "percent_screened_asian" integer,   NOT NULL,
    "percent_screened_black" integer,   NOT NULL,
    "percent_screened_hispanic" integer,   NOT NULL,
    "percent_screened_white" integer,   NOT NULL,
    "percent_vaccinated" integer,   NOT NULL,
    "quartile_21" integer,   NOT NULL,
    "percent_vaccinated_aian" integer,   NOT NULL,
    "percent_vaccinated_asian" integer,   NOT NULL,
    "percent_vaccinated_black" integer,   NOT NULL,
    "percent_vaccinated_hispanic" integer,   NOT NULL,
    "percent_vaccinated_white" integer,   NOT NULL,
    "cohort_size" integer,   NOT NULL,
    "high_school_graduation_rate" double   NOT NULL,
    "quartile_22" integer,   NOT NULL,
    "num_some_college" integer,   NOT NULL,
    "population" integer,   NOT NULL,
    "percent_some_college" double   NOT NULL,
    "95percent_ci_low_13" double   NOT NULL,
    "95percent_ci_high_13" double   NOT NULL,
    "quartile_23" integer,   NOT NULL,
    "num_unemployed" integer,   NOT NULL,
    "labor_force" integer,   NOT NULL,
    "percent_unemployed" double   NOT NULL,
    "quartile_24" integer,   NOT NULL,
    "percent_children_in_poverty" double   NOT NULL,
    "95percent_ci_low_14" double   NOT NULL,
    "95percent_ci_high_14" double   NOT NULL,
    "quartile_25" integer,   NOT NULL,
    "percent_children_in_poverty_aian" double   NOT NULL,
    "percent_children_in_poverty_asian" double   NOT NULL,
    "percent_children_in_poverty_black" double   NOT NULL,
    "percent_children_in_poverty_hispanic" double   NOT NULL,
    "percent_children_in_poverty_white" double   NOT NULL,
    "80th_percentile_income" integer,   NOT NULL,
    "20th_percentile_income" integer,   NOT NULL,
    "income_ratio" double   NOT NULL,
    "quartile_26" integer,   NOT NULL,
    "num_single_parent_households" integer,   NOT NULL,
    "num_households" integer,   NOT NULL,
    "percent_single_parent_households" double   NOT NULL,
    "95percent_ci_low_15" double   NOT NULL,
    "95percent_ci_high_15" double   NOT NULL,
    "quartile_27" integer,   NOT NULL,
    "num_associations" integer,   NOT NULL,
    "social_association_rate" double   NOT NULL,
    "quartile_28" integer,   NOT NULL,
    "annual_average_violent_crimes" double   NOT NULL,
    "violent_crime_rate" double   NOT NULL,
    "quartile_29" integer,   NOT NULL,
    "num_injury_deaths" integer,   NOT NULL,
    "injury_death_rate" double   NOT NULL,
    "95percent_ci_low_16" double   NOT NULL,
    "95percent_ci_high_16" double   NOT NULL,
    "quartile_30" integer,   NOT NULL,
    "injury_death_rate_aian" double   NOT NULL,
    "injury_death_rate_aian_95percent_ci_low" double   NOT NULL,
    "injury_death_rate_aian_95percent_ci_high" double   NOT NULL,
    "injury_death_rate_asian" double   NOT NULL,
    "injury_death_rate_asian_95percent_ci_low" double   NOT NULL,
    "injury_death_rate_asian_95percent_ci_high" double   NOT NULL,
    "injury_death_rate_black" double   NOT NULL,
    "injury_death_rate_black_95percent_ci_low" double   NOT NULL,
    "injury_death_rate_black_95percent_ci_high" double   NOT NULL,
    "injury_death_rate_hispanic" double   NOT NULL,
    "injury_death_rate_hispanic_95percent_ci_low" double   NOT NULL,
    "injury_death_rate_hispanic_95percent_ci_high" double   NOT NULL,
    "injury_death_rate_white" double   NOT NULL,
    "injury_death_rate_white_95percent_ci_low" double   NOT NULL,
    "injury_death_rate_white_95percent_ci_high" double   NOT NULL,
    "average_daily_pm2_5" double   NOT NULL,
    "quartile_31" integer,   NOT NULL,
    "presence_of_water_violation" text   NOT NULL,
    "quartile_32" integer,   NOT NULL,
    "percent_severe_housing_problems" double   NOT NULL,
    "95percent_ci_low_17" double   NOT NULL,
    "95percent_ci_high_17" double   NOT NULL,
    "severe_housing_cost_burden" double   NOT NULL,
    "severe_housing_cost_burden_95percent_ci_low" double   NOT NULL,
    "severe_housing_cost_burden_95percent_ci_high" double   NOT NULL,
    "overcrowding" double   NOT NULL,
    "overcrowding_95percent_ci_low" double   NOT NULL,
    "overcrowding_95percent_ci_high" double   NOT NULL,
    "inadequate_facilities" double   NOT NULL,
    "inadequate_facilities_95percent_ci_low" double   NOT NULL,
    "inadequate_facilities_95percent_ci_high" double   NOT NULL,
    "quartile_33" integer,   NOT NULL,
    "percent_drive_alone_to_work" double   NOT NULL,
    "95percent_ci_low_18" double   NOT NULL,
    "95percent_ci_high_18" double   NOT NULL,
    "quartile_34" integer,   NOT NULL,
    "percent_drive_alone_aian" double   NOT NULL,
    "percent_drive_alone_aian_95percent_ci_low" double   NOT NULL,
    "percent_drive_alone_aian_95percent_ci_high" double   NOT NULL,
    "percent_drive_alone_asian" double   NOT NULL,
    "percent_drive_alone_asian_95percent_ci_low" double   NOT NULL,
    "percent_drive_alone_asian_95percent_ci_high" double   NOT NULL,
    "percent_drive_alone_black" double   NOT NULL,
    "percent_drive_alone_black_95percent_ci_low" double   NOT NULL,
    "percent_drive_alone_black_95percent_ci_high" double   NOT NULL,
    "percent_drive_alone_hispanic" double   NOT NULL,
    "percent_drive_alone_hispanic_95percent_ci_low" double   NOT NULL,
    "percent_drive_alone_hispanic_95percent_ci_high" double   NOT NULL,
    "percent_drive_alone_white" double   NOT NULL,
    "percent_drive_alone_white_95percent_ci_low" double   NOT NULL,
    "percent_drive_alone_white_95percent_ci_high" double   NOT NULL,
    "num_workers_who_drive_alone" integer,   NOT NULL,
    "percent_long_commute_drives_alone" double   NOT NULL,
    "95percent_ci_low_19" double   NOT NULL,
    "95percent_ci_high_19" double   NOT NULL,
    "quartile_35" integer,   NOT NULL,
    "life_expectancy" double   NOT NULL,
    "95percent_ci_low_20" double   NOT NULL,
    "95percent_ci_high_20" double   NOT NULL,
    "life_expectancy_aian" double   NOT NULL,
    "life_expectancy_aian_95percent_ci_low" double   NOT NULL,
    "life_expectancy_aian_95percent_ci_high" double   NOT NULL,
    "life_expectancy_asian" double   NOT NULL,
    "life_expectancy_asian_95percent_ci_low" double   NOT NULL,
    "life_expectancy_asian_95percent_ci_high" double   NOT NULL,
    "life_expectancy_black" double   NOT NULL,
    "life_expectancy_black_95percent_ci_low" double   NOT NULL,
    "life_expectancy_black_95percent_ci_high" double   NOT NULL,
    "life_expectancy_hispanic" double   NOT NULL,
    "life_expectancy_hispanic_95percent_ci_low" double   NOT NULL,
    "life_expectancy_hispanic_95percent_ci_high" double   NOT NULL,
    "life_expectancy_white" double   NOT NULL,
    "life_expectancy_white_95percent_ci_low" double   NOT NULL,
    "life_expectancy_white_95percent_ci_high" double   NOT NULL,
    "num_deaths_2" integer,   NOT NULL,
    "age_adjusted_death_rate" double   NOT NULL,
    "95percent_ci_low_21" double   NOT NULL,
    "95percent_ci_high_21" double   NOT NULL,
    "age_adjusted_mortality_aian" double   NOT NULL,
    "age_adjusted_mortality_aian_95percent_ci_low" double   NOT NULL,
    "age_adjusted_mortality_aian_95percent_ci_high" double   NOT NULL,
    "age_adjusted_mortality_asian" double   NOT NULL,
    "age_adjusted_mortality_asian_95percent_ci_low" double   NOT NULL,
    "age_adjusted_mortality_asian_95percent_ci_high" double   NOT NULL,
    "age_adjusted_mortality_black" double   NOT NULL,
    "age_adjusted_mortality_black_95percent_ci_low" double   NOT NULL,
    "age_adjusted_mortality_black_95percent_ci_high" double   NOT NULL,
    "age_adjusted_mortality_hispanic" double   NOT NULL,
    "age_adjusted_mortality_hispanic_95percent_ci_low" double   NOT NULL,
    "age_adjusted_mortality_hispanic_95percent_ci_high" double   NOT NULL,
    "age_adjusted_mortality_white" double   NOT NULL,
    "age_adjusted_mortality_white_95percent_ci_low" double   NOT NULL,
    "age_adjusted_mortality_white_95percent_ci_high" double   NOT NULL,
    "num_deaths_3" integer,   NOT NULL,
    "child_mortality_rate" double   NOT NULL,
    "95percent_ci_low_22" double   NOT NULL,
    "95percent_ci_high_22" double   NOT NULL,
    "child_mortality_rate_aian" double   NOT NULL,
    "child_mortality_rate_aian_95percent_ci_low" double   NOT NULL,
    "child_mortality_rate_aian_95percent_ci_high" double   NOT NULL,
    "child_mortality_rate_asian" double   NOT NULL,
    "child_mortality_rate_asian_95percent_ci_low" double   NOT NULL,
    "child_mortality_rate_asian_95percent_ci_high" double   NOT NULL,
    "child_mortality_rate_black" double   NOT NULL,
    "child_mortality_rate_black_95percent_ci_low" double   NOT NULL,
    "child_mortality_rate_black_95percent_ci_high" double   NOT NULL,
    "child_mortality_rate_hispanic" double   NOT NULL,
    "child_mortality_rate_hispanic_95percent_ci_low" double   NOT NULL,
    "child_mortality_rate_hispanic_95percent_ci_high" double   NOT NULL,
    "child_mortality_rate_white" double   NOT NULL,
    "child_mortality_rate_white_95percent_ci_low" double   NOT NULL,
    "child_mortality_rate_white_95percent_ci_high" double   NOT NULL,
    "num_deaths_4" integer,   NOT NULL,
    "infant_mortality_rate" double   NOT NULL,
    "95percent_ci_low_23" double   NOT NULL,
    "95percent_ci_high_23" double   NOT NULL,
    "infant_mortality_rate_aian" double   NOT NULL,
    "infant_mortality_rate_aian_95percent_ci_low" double   NOT NULL,
    "infant_mortality_rate_aian_95percent_ci_high" double   NOT NULL,
    "infant_mortality_rate_asian" double   NOT NULL,
    "infant_mortality_rate_asian_95percent_ci_low" double   NOT NULL,
    "infant_mortality_rate_asian_95percent_ci_high" double   NOT NULL,
    "infant_mortality_rate_black" double   NOT NULL,
    "infant_mortality_rate_black_95percent_ci_low" double   NOT NULL,
    "infant_mortality_rate_black_95percent_ci_high" double   NOT NULL,
    "infant_mortality_rate_hispanic" double   NOT NULL,
    "infant_mortality_rate_hispanic_95percent_ci_low" double   NOT NULL,
    "infant_mortality_rate_hispanic_95percent_ci_high" double   NOT NULL,
    "infant_mortality_rate_white" double   NOT NULL,
    "infant_mortality_rate_white_95percent_ci_low" double   NOT NULL,
    "infant_mortality_rate_white_95percent_ci_high" double   NOT NULL,
    "percent_frequent_physical_distress" double   NOT NULL,
    "95percent_ci_low_24" double   NOT NULL,
    "95percent_ci_high_24" double   NOT NULL,
    "percent_frequent_mental_distress" double   NOT NULL,
    "95percent_ci_low_25" double   NOT NULL,
    "95percent_ci_high_25" double   NOT NULL,
    "percent_adults_with_diabetes" double   NOT NULL,
    "95percent_ci_low_26" double   NOT NULL,
    "95percent_ci_high_26" double   NOT NULL,
    "num_hiv_cases" integer,   NOT NULL,
    "hiv_prevalence_rate" double   NOT NULL,
    "num_food_insecure" integer,   NOT NULL,
    "percent_food_insecure" double   NOT NULL,
    "num_limited_access" double   NOT NULL,
    "percent_limited_access_to_healthy_foods" double   NOT NULL,
    "num_drug_overdose_deaths" integer,   NOT NULL,
    "drug_overdose_mortality_rate" double   NOT NULL,
    "95percent_ci_low_27" double   NOT NULL,
    "95percent_ci_high_27" double   NOT NULL,
    "drug_overdose_mortality_rate_aian" double   NOT NULL,
    "drug_overdose_mortality_rate_aian_95percent_ci_low" double   NOT NULL,
    "drug_overdose_mortality_rate_aian_95percent_ci_high" double   NOT NULL,
    "drug_overdose_mortality_rate_asian" double   NOT NULL,
    "drug_overdose_mortality_rate_asian_95percent_ci_low" double   NOT NULL,
    "drug_overdose_mortality_rate_asian_95percent_ci_high" double   NOT NULL,
    "drug_overdose_mortality_rate_black" double   NOT NULL,
    "drug_overdose_mortality_rate_black_95percent_ci_low" double   NOT NULL,
    "drug_overdose_mortality_rate_black_95percent_ci_high" double   NOT NULL,
    "drug_overdose_mortality_rate_hispanic" double   NOT NULL,
    "drug_overdose_mortality_rate_hispanic_95percent_ci_low" double   NOT NULL,
    "drug_overdose_mortality_rate_hispanic_95percent_ci_high" double   NOT NULL,
    "drug_overdose_mortality_rate_white" double   NOT NULL,
    "drug_overdose_mortality_rate_white_95percent_ci_low" double   NOT NULL,
    "drug_overdose_mortality_rate_white_95percent_ci_high" double   NOT NULL,
    "num_motor_vehicle_deaths" integer,   NOT NULL,
    "motor_vehicle_mortality_rate" double   NOT NULL,
    "95percent_ci_low_28" double   NOT NULL,
    "95percent_ci_high_28" double   NOT NULL,
    "mv_mortality_rate_aian" double   NOT NULL,
    "mv_mortality_rate_aian_95percent_ci_low" double   NOT NULL,
    "mv_mortality_rate_aian_95percent_ci_high" double   NOT NULL,
    "mv_mortality_rate_asian" double   NOT NULL,
    "mv_mortality_rate_asian_95percent_ci_low" double   NOT NULL,
    "mv_mortality_rate_asian_95percent_ci_high" double   NOT NULL,
    "mv_mortality_rate_black" double   NOT NULL,
    "mv_mortality_rate_black_95percent_ci_low" double   NOT NULL,
    "mv_mortality_rate_black_95percent_ci_high" double   NOT NULL,
    "mv_mortality_rate_hispanic" double   NOT NULL,
    "mv_mortality_rate_hispanic_95percent_ci_low" double   NOT NULL,
    "mv_mortality_rate_hispanic_95percent_ci_high" double   NOT NULL,
    "mv_mortality_rate_white" double   NOT NULL,
    "mv_mortality_rate_white_95percent_ci_low" double   NOT NULL,
    "mv_mortality_rate_white_95percent_ci_high" double   NOT NULL,
    "percent_insufficient_sleep" double   NOT NULL,
    "95percent_ci_low_29" double   NOT NULL,
    "95percent_ci_high_29" double   NOT NULL,
    "num_uninsured_2" integer,   NOT NULL,
    "percent_uninsured_2" double   NOT NULL,
    "95percent_ci_low_30" double   NOT NULL,
    "95percent_ci_high_30" double   NOT NULL,
    "num_uninsured_3" integer,   NOT NULL,
    "percent_uninsured_3" double   NOT NULL,
    "95percent_ci_low_31" double   NOT NULL,
    "95percent_ci_high_31" double   NOT NULL,
    "other_primary_care_provider_rate" double   NOT NULL,
    "other_primary_care_provider_ratio" text   NOT NULL,
    "percent_disconnected_youth" double   NOT NULL,
    "95percent_ci_low_32" double   NOT NULL,
    "95percent_ci_high_32" double   NOT NULL,
    "average_grade_performance" double   NOT NULL,
    "average_grade_performance_asian" double   NOT NULL,
    "average_grade_performance_black" double   NOT NULL,
    "average_grade_performance_hispanic" double   NOT NULL,
    "average_grade_performance_white" double   NOT NULL,
    "average_grade_performance_2" double   NOT NULL,
    "average_grade_performance_asian_2" double   NOT NULL,
    "average_grade_performance_black_2" double   NOT NULL,
    "average_grade_performance_hispanic_2" double   NOT NULL,
    "average_grade_performance_white_2" double   NOT NULL,
    "median_household_income" integer,   NOT NULL,
    "95percent_ci_low_33" double   NOT NULL,
    "95percent_ci_high_33" double   NOT NULL,
    "household_income_aian" integer,   NOT NULL,
    "household_income_aian_95percent_ci_low" double   NOT NULL,
    "household_income_aian_95percent_ci_high" double   NOT NULL,
    "household_income_asian" integer,   NOT NULL,
    "household_income_asian_95percent_ci_low" double   NOT NULL,
    "household_income_asian_95percent_ci_high" double   NOT NULL,
    "household_income_black" integer,   NOT NULL,
    "household_income_black_95percent_ci_low" double   NOT NULL,
    "household_income_black_95percent_ci_high" double   NOT NULL,
    "household_income_hispanic" integer,   NOT NULL,
    "household_income_hispanic_95percent_ci_low" double   NOT NULL,
    "household_income_hispanic_95percent_ci_high" double   NOT NULL,
    "household_income_white" integer,   NOT NULL,
    "household_income_white_95percent_ci_low" double   NOT NULL,
    "household_income_white_95percent_ci_high" double   NOT NULL,
    "percent_enrolled_in_free_or_reduced_lunch" double   NOT NULL,
    "segregation_index" double   NOT NULL,
    "segregation_index_2" double   NOT NULL,
    "homicide_rate" double   NOT NULL,
    "95percent_ci_low_34" double   NOT NULL,
    "95percent_ci_high_34" double   NOT NULL,
    "homicide_rate_aian" double   NOT NULL,
    "homicide_rate_aian_95percent_ci_low" double   NOT NULL,
    "homicide_rate_aian_95percent_ci_high" double   NOT NULL,
    "homicide_rate_asian" double   NOT NULL,
    "homicide_rate_asian_95percent_ci_low" double   NOT NULL,
    "homicide_rate_asian_95percent_ci_high" double   NOT NULL,
    "homicide_rate_black" double   NOT NULL,
    "homicide_rate_black_95percent_ci_low" double   NOT NULL,
    "homicide_rate_black_95percent_ci_high" double   NOT NULL,
    "homicide_rate_hispanic" double   NOT NULL,
    "homicide_rate_hispanic_95percent_ci_low" double   NOT NULL,
    "homicide_rate_hispanic_95percent_ci_high" double   NOT NULL,
    "homicide_rate_white" double   NOT NULL,
    "homicide_rate_white_95percent_ci_low" double   NOT NULL,
    "homicide_rate_white_95percent_ci_high" double   NOT NULL,
    "num_deaths_5" integer,   NOT NULL,
    "suicide_rate_age_adjusted" double   NOT NULL,
    "95percent_ci_low_35" double   NOT NULL,
    "95percent_ci_high_35" double   NOT NULL,
    "crude_rate" double   NOT NULL,
    "suicide_rate_aian" double   NOT NULL,
    "suicide_rate_aian_95percent_ci_low" double   NOT NULL,
    "suicide_rate_aian_95percent_ci_high" double   NOT NULL,
    "suicide_rate_asian" double   NOT NULL,
    "suicide_rate_asian_95percent_ci_low" double   NOT NULL,
    "suicide_rate_asian_95percent_ci_high" double   NOT NULL,
    "suicide_rate_black" double   NOT NULL,
    "suicide_rate_black_95percent_ci_low" double   NOT NULL,
    "suicide_rate_black_95percent_ci_high" double   NOT NULL,
    "suicide_rate_hispanic" double   NOT NULL,
    "suicide_rate_hispanic_95percent_ci_low" double   NOT NULL,
    "suicide_rate_hispanic_95percent_ci_high" double   NOT NULL,
    "suicide_rate_white" double   NOT NULL,
    "suicide_rate_white_95percent_ci_low" double   NOT NULL,
    "suicide_rate_white_95percent_ci_high" double   NOT NULL,
    "num_firearm_fatalities" integer,   NOT NULL,
    "firearm_fatalities_rate" double   NOT NULL,
    "95percent_ci_low_36" double   NOT NULL,
    "95percent_ci_high_36" double   NOT NULL,
    "firearm_fatalities_rate_aian" double   NOT NULL,
    "firearm_fatalities_rate_aian_95percent_ci_low" double   NOT NULL,
    "firearm_fatalities_rate_aian_95percent_ci_high" double   NOT NULL,
    "firearm_fatalities_rate_asian" double   NOT NULL,
    "firearm_fatalities_rate_asian_95percent_ci_low" double   NOT NULL,
    "firearm_fatalities_rate_asian_95percent_ci_high" double   NOT NULL,
    "firearm_fatalities_rate_black" double   NOT NULL,
    "firearm_fatalities_rate_black_95percent_ci_low" double   NOT NULL,
    "firearm_fatalities_rate_black_95percent_ci_high" double   NOT NULL,
    "firearm_fatalities_rate_hispanic" double   NOT NULL,
    "firearm_fatalities_rate_hispanic_95percent_ci_low" double   NOT NULL,
    "firearm_fatalities_rate_hispanic_95percent_ci_high" double   NOT NULL,
    "firearm_fatalities_rate_white" double   NOT NULL,
    "firearm_fatalities_rate_white_95percent_ci_low" double   NOT NULL,
    "firearm_fatalities_rate_white_95percent_ci_high" double   NOT NULL,
    "non_petitioned_cases" text   NOT NULL,
    "petitioned_cases" text   NOT NULL,
    "denominator" integer,   NOT NULL,
    "juvenile_arrest_rate" double   NOT NULL,
    "average_traffic_volume_per_meter_of_major_roadways" double   NOT NULL,
    "num_homeowners" integer,   NOT NULL,
    "percent_homeowners" double   NOT NULL,
    "95percent_ci_low_37" double   NOT NULL,
    "95percent_ci_high_37" double   NOT NULL,
    "num_households_with_severe_cost_burden" integer,   NOT NULL,
    "percent_severe_housing_cost_burden" double   NOT NULL,
    "95percent_ci_low_38" double   NOT NULL,
    "95percent_ci_high_38" double   NOT NULL,
    "population_2" integer,   NOT NULL,
    "percent_less_than_18_years_of_age" double   NOT NULL,
    "percent_65_and_over" double   NOT NULL,
    "num_black" integer,   NOT NULL,
    "percent_black" double   NOT NULL,
    "num_american_indian_alaska_native" integer,   NOT NULL,
    "percent_american_indian_alaska_native" double   NOT NULL,
    "num_asian" integer,   NOT NULL,
    "percent_asian" double   NOT NULL,
    "num_native_hawaiian_other_pacific_islander" integer,   NOT NULL,
    "percent_native_hawaiian_other_pacific_islander" double   NOT NULL,
    "num_hispanic" integer,   NOT NULL,
    "percent_hispanic" double   NOT NULL,
    "num_non_hispanic_white" integer,   NOT NULL,
    "percent_non_hispanic_white" double   NOT NULL,
    "num_not_proficient_in_english" integer,   NOT NULL,
    "percent_not_proficient_in_english" double   NOT NULL,
    "95percent_ci_low_39" double   NOT NULL,
    "95percent_ci_high_39" double   NOT NULL,
    "percent_female" double   NOT NULL,
    "num_rural" integer,   NOT NULL,
    "percent_rural" double   NOT NULL
);

CREATE TABLE "birth_death_rate" (
    "Notes" text   NOT NULL,
    "County" text   NOT NULL,
    "County Code" integer   NOT NULL,
    "Deaths" integer   NOT NULL,
    "Births" integer   NOT NULL,
    "Death Rate" text   NOT NULL
);

CREATE TABLE "agg_county_donors" (
    "index" bigint   NOT NULL,
    "blue_amt" bigint   NOT NULL,
    "red_amt" bigint   NOT NULL,
    "other_amt" bigint   NOT NULL,
    "total_amt" bigint   NOT NULL,
    "blue_num" bigint   NOT NULL,
    "red_num" bigint   NOT NULL,
    "other_num" bigint   NOT NULL,
    "total_num" bigint   NOT NULL,
    "county" text   NOT NULL,
    "state" text   NOT NULL,
    "election_year" bigint   NOT NULL
);

CREATE TABLE "agg_county_votores" (
    "index" bigint   NOT NULL,
    "blue_votes" bigint   NOT NULL,
    "red_votes" bigint   NOT NULL,
    "other_votes" bigint   NOT NULL,
    "total_votes" bigint   NOT NULL,
    "county" text   NOT NULL,
    "state" text   NOT NULL,
    "election_year" bigint   NOT NULL,
    "PopPct_Urban" double   NOT NULL,
    "Unemployment" double   NOT NULL,
    "PopDen_Urban" double   NOT NULL,
    "PopPct_Rural" double   NOT NULL,
    "PopDen_Rural" double   NOT NULL,
    "winning_party" text   NOT NULL
);

ALTER TABLE "committees" ADD CONSTRAINT "fk_committees_CAND_ID" FOREIGN KEY("CAND_ID")
REFERENCES "candidates" ("CAND_ID");

ALTER TABLE "donations" ADD CONSTRAINT "fk_donations_CMTE_ID" FOREIGN KEY("CMTE_ID")
REFERENCES "committees" ("CMTE_ID");

ALTER TABLE "donations" ADD CONSTRAINT "fk_donations_ZIP" FOREIGN KEY("ZIP")
REFERENCES "postal_codes" ("zip");

ALTER TABLE "education" ADD CONSTRAINT "fk_education_FIPS Code" FOREIGN KEY("FIPS Code")
REFERENCES "postal_codes" ("stcountyfp");

ALTER TABLE "unemployment" ADD CONSTRAINT "fk_unemployment_fips" FOREIGN KEY("fips")
REFERENCES "postal_codes" ("stcountyfp");

ALTER TABLE "birth_death_rate" ADD CONSTRAINT "fk_birth_death_rate_County Code" FOREIGN KEY("County Code")
REFERENCES "postal_codes" ("stcountyfp");

